AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 145

Metrics/BlockLength:
  Max: 45

Style/Documentation:
  Enabled: false

AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatStringToken:
  Enabled: false